import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import security from "eslint-plugin-security";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // L6.INSECURE_PATTERNS_ARE_SCANNED — the local half of that rule. semgrep
  // runs in CI; this catches the same shapes in the editor, where they are
  // cheapest to not write.
  security.configs.recommended,
  {
    rules: {
      // Every sink this flagged writes a key built from our own content
      // (`capsule.id`, a turn counter) — not from user or model input. Model
      // output reaches an object only through `parsePortfolioSpec`, which
      // gates it on the zod catalog and `validateSpec` first. Six permanent
      // warnings would teach us to skim lint output, which costs more than
      // the rule pays here.
      "security/detect-object-injection": "off",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Mutation fixtures are deliberately broken repositories, one per rule.
    // A linter reads them as defects; they are the proof the checks fire.
    ".software-factory/mutations/**",
    // Generated by `npm run build:worker`: web-llm bundled for the worker.
    // 6.5 MB of vendor output, and not ours to lint.
    "public/llm-worker.js",
  ]),
]);

export default eslintConfig;
